Restaurant.create(name: "Flamengo Dragon", address: "Rua A, 123", phone_number: "1234-5678", category: "chinese")
Restaurant.create(name: "Flamengo Bigger", address: "Rua B, 456", phone_number: "2345-6789", category: "italian")
Restaurant.create(name: "Flamengo Master", address: "Rua C, 789", phone_number: "3456-7890", category: "japanese")
Restaurant.create(name: "Le Flamengo", address: "Rua D, 101", phone_number: "4567-8901", category: "french")
Restaurant.create(name: "Flamengo King", address: "Rua E, 202", phone_number: "5678-9012", category: "belgian")
